### ISSUE TITLE
仅仅在 redirected 的情况下使用 HttpDNS？

### ISSUE THREAD

**Issue by ritchie7** [DNSPod/httpdns-sdk-ios#11]
[startRequest](https://github.com/DNSPod/httpdns-sdk-ios/blob/067552b908f167f51c7e33af360b63fec1f9cba8/MSDKDns/MSDKDnsHttpMessageTools.m#L111) 中没有用到 ip 呀，那其实不没有用到 HttpDNS？

这样只用重定向才能赚到钱吧 🤓

**Comment by HuYuee** [comment]
这个类是去解决SNI等一些问题的，在普通请求中也可以使用HTTPDNS的
