### ISSUE TITLE
使用 MSDKDnsHttpMessageTools 的代码拦截请求再发送，有crash产生

### ISSUE THREAD

**Issue by 451222664** [DNSPod/httpdns-sdk-ios#26]
已崩溃：com.apple.CFNetwork.CustomProtocols
EXC_BREAKPOINT 0x00000001a3dd4b90

0 libobjc.A.dylib objc_opt_respondsToSelector + 48
1 CoreFoundation _inputStreamCallbackFunc + 52
2 CoreFoundation _signalEventSync + 216
3 CoreFoundation _cfstream_shared_signalEventSync + 392
4 CoreFoundation __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
5 CoreFoundation __CFRunLoopDoSource0 + 208
6 CoreFoundation __CFRunLoopDoSources0 + 368
7 CoreFoundation __CFRunLoopRun + 828
8 CoreFoundation CFRunLoopRunSpecific + 600
9 CFNetwork _CFURLStorageSessionDisableCache + 60032
10 Foundation __NSThread__start__ + 808
11 libsystem_pthread.dylib _pthread_start + 148
12 libsystem_pthread.dylib thread_start + 8

**Comment by HuYuee** [comment]
能具体描述下使用场景和提供下具体的crash地方的代码吗？这样方便复现问题

**Comment by 451222664** [comment]
把 MSDKDnsHttpMessageTools 注册进Alamofire session的protocolClass，拦截请求后再用Tools里面cfnetwork去发送。复现概率很低。
目前在dealloc加上销毁代理，线上就没有出现问题了。
- (void)dealloc {
    [_inputStream removeFromRunLoop:_curRunLoop forMode:NSRunLoopCommonModes];
    [_inputStream setDelegate:nil];
    [_inputStream close];
    _inputStream = nil;
}
